grafana:
  adminUser: admin

  service:
    type: NodePort

prometheus:
  service:
    type: NodePort

alertmanager:
  service:
    type: NodePort

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
